### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vdoucet** [rlindner/node-red-contrib-sma-webconnect#1]
Hi, I tried it on my SMA SunnyBoy 1.5.
When I trigger the function, it does give the following output : "Error: connect ECONNREFUSED 192.168.1.85:443" ... could the port be different?
I'm using "user" and the same password as the one I use to access the SMA local web server.
A the bottom of the web interface it says : "Firmware version: 2.5.1.R" and "WLAN IP address: 192.168.1.85" (as well as my serial #)

**Comment by rlindner** [comment]
But you can reach the webinterface with https://192.168.1.85 ?

**Comment by vdoucet** [comment]
I can reach in http but not in https !

**Comment by rlindner** [comment]
Alright, that sounds to be the issue then. I'll put it onto my list to support plain HTTP connections.

**Comment by rlindner** [comment]
I've updated the node to include a checkbox in the configuration to disable HTTPS now. But I'm not able to test it, because my inverter supports HTTPS only (it redirects to HTTPS). Further the firmware version of my inverter is 1.1.18.R, so I've doubts it's running the same software. But give it a try, I'm very happy for any feedback.

**Comment by vdoucet** [comment]
It's working ! ... but it's late and no more sun ... I'll have to wait tomorrow to see actual values (all are at 0 now which is normal)

**Comment by vdoucet** [comment]
It's working ! Thanks for your work !
I'm polling every 30s and I put that on a graph in node-red for the time being.
It is weird that with 1.1.18R you have https and not anymore with 2.5.1R (I would have thought it could happen the other way around).
Thanks again, great work

**Comment by rlindner** [comment]
Neat, thanks for the positive feedback! I could imagine they use different firmwares for the different hardware with each having it's own version history. Maybe the Webinterface is only a small part of the firmware as well. My inverter is quite new, it's the latest product line, Sunny Tripower 10.0, installed in April 2019, so assume the firmware is pretty up to date.

As it's working now, I'm gonna close this issue, but feel free to open a new one or comment here if any further feedback/questions come up.

**Comment by gabrio79** [comment]
> But you can reach the webinterface with https://192.168.1.85 ?

I can't reach he webinterface ... how you enable it?
