### ISSUE TITLE
List of needed nodes 

### ISSUE THREAD

**Issue by Tonio16** [rlindner/node-red-contrib-sma-webconnect#28]
Hello

I have an issue with missing nodes, IDxxxx. It would be nice which one has to be installed.

Tx

Antoine

**Comment by rlindner** [comment]
Hey Antoine, this node doesn't build upon any other nodes.

**Comment by Tonio16** [comment]
Sorry, I am not able to use it due to missing nodes and no idea of which packages I shall install. Here the one that are missing.
ui_chart (x2)
ui_gauge (x1)
ui_group (x1)
ui_tab (x1)
ui_template (x2)
ui_text (x2)

I tried some node but my node red is broken yet.


Antoine

**Comment by rlindner** [comment]
This node doesn't use any of these, but it looks like this package might solve your issue:
https://flows.nodered.org/node/node-red-dashboard

**Comment by rlindner** [comment]
@Tonio16 Could you solve your issue?

**Comment by Tonio16** [comment]
No because I can't uninstalled some ui packages. I would need to make a new install of node red and I have no time for that. 

Antoine
