### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by halfagascan** [rlindner/node-red-contrib-sma-webconnect#36]
First time user of nodered, and of using your package, below is my error

npm audit
# npm audit report

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
No fix available
node_modules/request
  node-red-contrib-sma-webconnect  *
  Depends on vulnerable versions of request
  Depends on vulnerable versions of requestretry
  node_modules/node-red-contrib-sma-webconnect
  requestretry  *
  Depends on vulnerable versions of request
  node_modules/requestretry

3 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

**Comment by rlindner** [comment]
Hi, the mentioned vulnerability arises from the [request](https://github.com/request/request/) dependency and doesn't have a patched version as of now. But normally this should only raise a warning and not prevent you from using it.

**Comment by halfagascan** [comment]
ok, thanks, I'll close
