### ISSUE TITLE
Etimedout error when trying to connect to SB300tl-21

### ISSUE THREAD

**Issue by WombatHollow** [rlindner/node-red-contrib-sma-webconnect#4]
i have spent a day trying to get this to talk to SB3000 (2 of).  They both connect as user through Sunny Explorer over speedwire inc,uding logging into them as a user [http only) aas this is on a local home network.
But trying to connecting using this node only produce a etimedout error (x3).
Occurs on both Node-red running on a Raspi 3b and w10 desktop (in powershell]
Ran TCPDump on Raspi and captured all traffic between Pi and SB, you just see severa similiar TCP messages from Pi to SB but no response  I do see ICMP and ARP  traffic from Pi to SB, and SB responds to them.
I also tcpdump on W10 machine communication succesfully with both SB using Sunny Explorer.  I see only UDP traffic from SB to the W10 machine...strange as I expected request fro Sunny Explorer.
So what is missing that is stopping this working?

**Comment by HoLo85** [comment]
I think this works only with inverters that provide a separate webinterface.
It works with my TRIPOWER 10.0 and it just connects to the inverter and reads the data the same way the webinterface reads it.
It gets the data in a JSON format from the inverter and picks out these informations:

> "6100_0046E500", // phase 1 voltage
            "6100_0046E600", // phase 2 voltage
            "6100_0046E700", // phase 3 voltage
            "6100_40263F00", // power
            "6100_40463600", // grid feedin
            "6100_40463700" // grid consumption

**Comment by WombatHollow** [comment]
Thanks for that   both seem to use Webconnect (SB3000 has built-in  Webconnect/speedwire i terface) so expect s8miliar but obviously different.


What documentation did you find that documented the web interface?




Sent from Outlook Mobile







On Sat, May 30, 2020 at 3:46 AM +1000, "HoLo85" <notifications@github.com> wrote:















I think this works only with inverters that provide a separate webinterface.

It works with my TRIPOWER 10.0 and it just connects to the inverter and reads the data the same way the webinterface reads it.

It gets the data in a JSON format from the inverter and picks out these informations:



"6100_0046E500", // phase 1 voltage

"6100_0046E600", // phase 2 voltage

"6100_0046E700", // phase 3 voltage

"6100_40263F00", // power

"6100_40463600", // grid feedin

"6100_40463700" // grid consumption

**Comment by HoLo85** [comment]
I connected to the webinterface of my inverter/storage with a browser and used the network tools to read the traffic from the inverter, it think @rlindner did it the same way.
Does your SB3000 provide a webinterface if you connect to it and does it display the values there, or do you need a separate software to read the output of the inverter?

**Comment by rlindner** [comment]
> What documentation did you find that documented the web interface?

> I connected to the webinterface of my inverter/storage with a browser and used the network tools to read the traffic from the inverter, it think @rlindner did it the same way.

That's correct, I'm not aware on any documentation. But the web interface is quite thankful, you can find the IDs for the values in the HTML and it has a JSON endpoint to retrieve the values from there by these IDs.
